working_dir: /mnt/storage11Tb_3/ArctiVerse

samples_dir: /mnt/storage11Tb_3/ArctiVerse/00.Data/00.Sequencing/00.DNA/01.MinION
basecall_dir: /mnt/storage11Tb_3/ArctiVerse/00.Data/01.Basecalling/00.DNA/01.MinION
correct_dir : /mnt/storage11Tb_3/ArctiVerse/00.Data/02.Correcting/00.DNA/01.MinION
bin_dir : /mnt/storage11Tb_3/ArctiVerse/00.Data/03.Binning/00.DNA/01.MinION
assembly_dir: /mnt/storage11Tb_3/ArctiVerse/01.Assembly/00.Genomes/01.Assembly

samples : 
  #- RCC7838
  #- RCC7839
  - RCC7840
  #- RCC7841
  #- RCC7847
  #- RCC7848
  #- RCC7855


