name: Validate Snakemake Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-snakemake:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python et Snakemake
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Snakemake
        run: |
          python -m pip install --upgrade pip
          pip install snakemake

      # Étape 3 : Valider le workflow avec un dry-run
      - name: Validate Snakemake workflow
        run: |
          snakemake --cores 1 --dry-run