name: Validate Snakemake Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  validate-snakemake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and install Snakemake
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Snakemake
        run: |
          python -m pip install --upgrade pip
          pip install snakemake

      # Step 3: Run Snakemake dry-run with test data
      - name: Validate Snakemake workflow with test data
        run: |
          snakemake --configfile test/config_test.yaml --cores 10 -sdm conda